### ISSUE TITLE
accessKeyId / secretAccessKey ?

### ISSUE THREAD

**Issue by andyfenelon** [packetloop/connect-dynamodb-session#13]
sorry if i've missed something but where do you put your accessKeyId / secretAccessKey ?

also would this work for koa ?

**Comment by nkbt** [comment]
They are coming from ENV vars and automatically picked up by `aws-sdk`, we do not ever specify keys/secrets anywhere in the app.

**Comment by nkbt** [comment]
Never used `koa`, but I assume it should be able to use standard SessionStore implementation, which this thing is. If it does not - then prob not...

**Comment by andyfenelon** [comment]
ok thanks.
