### ISSUE TITLE
require and es6

### ISSUE THREAD

**Issue by rbarilani** [packetloop/connect-dynamodb-session#14]
Hi, 

The documentation says:

```js
const DynamoStore = require('connect-dynamodb-session')(session);
```

But in my environment: 

```
node v6.9.1
npm 3.10.8
```

You should do:
```js
const DynamoStore = require('connect-dynamodb-session').default(session);
```

Probably it's babel 6, you might be interested to this: https://github.com/59naga/babel-plugin-add-module-exports

**Comment by nkbt** [comment]
Thanks gor the report!

Do you want to PR udate for the README?

**Comment by rbarilani** [comment]
@nkbt I think until nodejs community figure out what to do with es6 module loader we should stick to:

```
require('connect-dynamodb-session')(session);
```

By doing some "magic" when transpiling. I will open a PR tomorrow.
